config/routes.rb
Rails.application.routes.draw do
  get 'menu' => 'menu_pages#menu'

  get 'password_resets/new'

  get 'password_resets/edit'

  get 'sessions/new'

  get 'signup' => 'user_pages#regist'

  get 'user/profile' =>'user_pages#profile'

  post 'signup/confirm' => 'user_pages#confirm'

  #get 'login' =>'user_pages#login'

  get 'about' =>'static_pages/about'

  root 'static_pages#home'

  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  resources :user_pages
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :remember_token, :activation_token, :reset_token
  before_save   :downcase_email
  before_create :create_activation_digest
  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }

  # 与えられた文字列のハッシュ値を返す
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # ランダムなトークンを返す
  def User.new_token
    SecureRandom.urlsafe_base64
  end

  # 永続的セッションで使用するユーザーをデータベースに記憶する
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  # トークンがダイジェストと一致したらtrueを返す
  def authenticated?(attribute, token)
    digest = send("#{attribute}_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end

  # ユーザーログインを破棄する
  def forget
    update_attribute(:remember_digest, nil)
  end

  # アカウントを有効にする
  def activate
    update_attribute(:activated,    true)
    update_attribute(:activated_at, Time.zone.now)
  end

  # 有効化用のメールを送信する
  def send_activation_email
    UserMailer.account_activation(self).deliver_now
  end

  # パスワード再設定の属性を設定する
  def create_reset_digest
    self.reset_token = User.new_token
    update_attribute(:reset_digest,  User.digest(reset_token))
    update_attribute(:reset_sent_at, Time.zone.now)
  end

  # パスワード再設定のメールを送信する
  def send_password_reset_email
    UserMailer.password_reset(self).deliver_now
  end

  # パスワード再設定の期限が切れている場合はtrueを返す
  def password_reset_expired?
    reset_sent_at < 2.hours.ago
  end

  private

    # メールアドレスをすべて小文字にする
    def downcase_email
      self.email = email.downcase
    end

    # 有効化トークンとダイジェストを作成および代入する
    def create_activation_digest
      self.activation_token  = User.new_token
      self.activation_digest = User.digest(activation_token)
    end
end

app/controllers/account_activations_controller.rb
class AccountActivationsController < ApplicationController
  def edit
    user = User.find_by(email: params[:email])
    if user && !user.activated? && user.authenticated?(:activation, params[:id])
      user.activate
      log_in user
      flash[:success] = "本登録が完了しました。"
      redirect_to user_page_url(user)
    else
      flash[:danger] = "すでに本登録が完了している、または本登録用リンクが無効です。"
      redirect_to root_url
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/menu_pages_controller.rb
class MenuPagesController < ApplicationController
  def menu
  end

end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  before_action :get_user,   only: [:edit, :update]
  before_action :valid_user, only: [:edit, :update]

  def new
  end

  def create
    @user = User.find_by(email: params[:password_reset][:email].downcase)
    if @user
      @user.create_reset_digest
      @user.send_password_reset_email
      flash[:info] = "入力されたメールアドレスへパスワード再設定用のメールを送信しました。"
      redirect_to root_url
    else
      flash.now[:danger] = "入力されたメールアドレスが間違っています。"
      render 'new'
    end
  end

  def edit
  end

  def update
    if params[:user][:password].empty?
      @user.errors.add(:password,  "can't be empty")
      render 'edit'
    elsif @user.update_attributes(user_params)
      log_in @user
      flash[:success] = "Password has been reset."
      redirect_to user_page_url(@user)
    else
      render 'edit'
    end
  end

  private

    def user_params
      params.require(:user).permit(:password, :password_confirmation)
    end

    # Beforeフィルタ

    def get_user
      @user = User.find_by(email: params[:email])
    end

    # 正しいユーザーを確認する
    def valid_user
      unless (@user && @user.activated? &&
              @user.authenticated?(:reset, params[:id]))
        redirect_to root_url
      end
    end

    # 再設定用トークンが期限切れかどうかを確認する
    def check_expiration
      if @user.password_reset_expired?
        flash[:danger] = "Password reset has expired."
        redirect_to new_password_reset_url
      end
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      if user.activated?
        log_in user
        params[:session][:remember_me] == '1' ? remember(user) : forget(user)
        redirect_to user_page_url(user)
      else
        message  = "本登録が完了していません。 "
        message += "送信されたメールから本登録を完了して下さい。"
        flash[:warning] = message
        redirect_to root_url
      end
    else
      flash.now[:danger] = "メールアドレスまたはパスワードが間違っています。"
      render 'new'
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end
end

app/controllers/user_pages_controller.rb
class UserPagesController < ApplicationController
  def regist
    @user = User.new
  end

  def profile
  end

  def login
  end

  def show
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)
    if params[:back]
      render 'regist'
    elsif @user.save
      @user.send_activation_email
      flash[:info] = "入力されたメールアドレスにメールを送信しました。"
      redirect_to root_url
    else
      render 'regist'
    end
  end

  def confirm
    @user = User.new(user_params)
    render 'regist' if @user.invalid?
  end

  private

  def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
  end
end

app/helpers/account_activations_helper.rb
module AccountActivationsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/menu_pages_helper.rb
module MenuPagesHelper
end

app/helpers/password_resets_helper.rb
module PasswordResetsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  # 渡されたユーザーでログインする
  def log_in(user)
    session[:user_id] = user.id
  end

  # ユーザーを永続的セッションに記憶する
  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  # 現在ログインしているユーザーを返す (ユーザーがログイン中の場合のみ)
  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(:remember, cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end

  # ユーザーがログインしていればtrue、その他ならfalseを返す
  def logged_in?
    !current_user.nil?
  end

  # 永続的セッションを破棄する
  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

  # 現在のユーザーをログアウトする
  def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/user_pages_helper.rb
module UserPagesHelper
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/layouts/_footer.html.erb

<!-- Footer
================================================== -->
<footer>
   <div class="row">
      <div class="six columns info">
         <div class="footer-logo">
            <a href="#">
               <%= image_tag 'footer-logo.png' %>
            </a>
         </div>
         <p>This is Photoshop's version  of Lorem Ipsum. Proin gravida nibh vel velit auctor aliquet.
         Aenean sollicitudin, lorem quis bibendum auctor, nisi elit consequat ipsum, nec sagittis sem
         nibh id elit. Duis sed odio sit amet nibh vulputate cursus a sit amet mauris.
         </p>
      </div>
      <div class="six columns right-cols">
         <div class="row">
            <div class="columns">
              <h3 class="address">Come Visit</h3>
               <p>
               1600 Amphitheatre Parkway<br>
               Mountain View, CA<br>
               94043 US
               </p>
            </div>
            <div class="columns">
               <h3 class="social">socialize</h3>
               <ul>
                  <li><a href="#">Facebook</a></li>
                  <li><a href="#">Twitter</a></li>
                  <li><a href="#">GooglePlus</a></li>
               </ul>
            </div>
            <div class="columns last">
               <h3 class="contact">Contact Us</h3>
               <ul>
                 <li><a href="tel:0822915050">082-291-5050</a></li>
                 <li><a href="mailto:inoue@hsc.ac.jp">inoue@hsc.ac.jp</a></li>
               </ul>
            </div>
         </div> <!-- Nested Row End -->
      </div>
      <p class="copyright">&copy; 2016 楽Laクック | Created by <a title="Styleshout" href="http://www.hsc.ac.jp/">Hiroshima Computer College</a></p>
      <div id="go-top">
         <a class="smoothscroll" title="Back to Top" href="#hero"><i class="icon-up-open"></i></a>
      </div>
   </div> <!-- Row End -->
</footer> <!-- Footer End-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!--[if lt IE 8 ]><html class="no-js ie ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]><html class="no-js ie ie8" lang="en"> <![endif]-->
<!--[if IE 9 ]><html class="no-js ie ie9" lang="en"> <![endif]-->
<!--[if (gte IE 8)|!(IE)]><!--><html class="no-js" lang="ja"> <!--<![endif]-->
<head>

   <!--- Basic Page Needs
   ================================================== -->
   <meta charset="utf-8">
	<title>今夜の献立に悩んだら／質問に答えるだけ！ 楽Laクック</title>
	<meta name="description" content="">
	<meta name="author" content="">

   <!-- Mobile Specific Metas
   ================================================== -->
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  	<%= favicon_link_tag 'favicon.png' %>
  </head>
<body>


  <!-- Header
  ================================================== -->
  <header>

     <div class="logo">
        <a href="http://www.rakulacook.com/"><%= image_tag 'logo.png' %></a>
     </div>

     <nav id="nav-wrap">

        <a class="mobile-btn" href="#nav-wrap" title="Show navigation">Show Menu</a>
       <a class="mobile-btn" href="#" title="Hide navigation">Hide Menu</a>

        <ul id="nav" class="nav">

          <% if logged_in? %>
            <li><%= link_to "マイページ", user_page_path(current_user) %></li>
            <li><%= link_to "設定", '#' %></li>
            <li><%= link_to "ログアウト", logout_path, method: "delete" %></li>
          <% else %>
            <li><%= link_to "ログイン", login_path %></li>
            <li><%= link_to "会員登録", signup_path %></li>
          <% end %>

          <!-- 非ログインユーザ-->
           <!--<li><a href="http://www.rakulacook.com/signup">ユーザ登録</a></li>
           <li><a href="http://www.rakulacook.com/login">ログイン</a></li>-->
         <!-- ログインユーザ
           <li>広コン太郎さん<a  href="#mymenu">（マイメニュー）</a></li>
           <li><a href="#logout">ログアウト</a></li>
         -->
        </ul> <!-- end #nav -->

     </nav> <!-- end #nav-wrap -->

  </header> <!-- Header End -->


<br /><br /><br />
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

<%= yield %>

<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
</body>
</html>

app/views/menu_pages/menu.html.erb
<h1>質問</h1>
<br />



<%= render 'layouts/footer' %>

app/views/password_resets/edit.html.erb
<h1>パスワード再設定</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user, url: password_reset_path(params[:id])) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= hidden_field_tag :email, @user.email %>

      <%= f.label :password, "パスワード" %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "パスワード（確認）" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "メールを送信する", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>
<%= render 'layouts/footer' %>

app/views/password_resets/new.html.erb
<h1>パスワード再設定</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(:password_reset, url: password_resets_path) do |f| %>
      <%= f.label :email, "メールアドレス" %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.submit "パスワードを再設定する", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>
<%= render 'layouts/footer' %>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/new.html.erb
<h1>Log in</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(:session, url: login_path) do |f| %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.submit "Log in", class: "btn btn-primary" %>
    <% end %>

    <p>New user? <%= link_to "Sign up now!", signup_path %></p>
  </div>
</div>
<%= render 'layouts/footer' %>

app/views/static_pages/about.html.erb
<h1>StaticPages#about</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>

app/views/static_pages/home.html.erb
<!-- Homepage Hero
  ================================================== -->
  <section id="hero">

    <div class="row">

      <div class="twelve columns">

        <div class="hero-text">
          <h1 class="responsive-headline">献立提案的なタイトル</h1>

          <p>何かしらのメッセージをここに記述。何かしらのメッセージをここに記述。何かしらのメッセージをここに記述。何かしらのメッセージをここに記述。</p>
        </div>

           <div class="buttons">
              <!-- スタートクリックで献立提案プロセスを開始する -->
              <!--<a class="button trial" href="#">Start</a>-->
              <%= link_to "スタート", {:controller => "menu_pages" , :action => "menu"}, {:class => "button trial"} %>
              <!--<a class="button learn-more smoothscroll" href="#features">ユーザ登録する</a>-->
           </div>

           <div class="hero-image">
              <%= image_tag 'hero-image' %>
           </div>

      </div>

    </div>

  </section> <!-- Homepage Hero end -->

  <!-- Screenshots
  ================================================== -->
  <section id="screenshots">

     <div class="row section-head">

        <h1>人気の献立</h1>
<!--　ログインしてない場合はスクリーンショット　ログインしていれば献立ページへのリンク -->
        <p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam,
        eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam
        voluptatem quia voluptas sit aspernatur aut odit aut fugit.
        </p>

     </div>

     <div class="row">

        <div class="twelve columns">

           <!-- screenshots-wrapper -->
           <div id="screenshots-wrapper" class="bgrid-quarters s-bgrid-thirds cf">

              <div class="columns item">
                 <div class="item-wrap">

                    <a href="#" data-imagelightbox="a" >
                       <%= image_tag 'screenshots/line-icons.jpg' %>
                       <div class="overlay"></div>
                       <div class="link-icon"><i class="icon-plus"></i></div>
                    </a>

                 </div>
             </div> <!-- item end -->

              <div class="columns item">
                 <div class="item-wrap">

                    <a href="#" data-imagelightbox="a" >
                       <%= image_tag 'screenshots/hipster.jpg' %>
                       <div class="overlay"></div>
                       <div class="link-icon"><i class="icon-plus"></i></div>
                    </a>

                 </div>
             </div> <!-- item end -->

              <div class="columns item">
                 <div class="item-wrap">

                    <a href="#" data-imagelightbox="a" >
                       <%= image_tag 'screenshots/authentic-vintage.jpg' %>
                       <div class="overlay"></div>
                       <div class="link-icon"><i class="icon-plus"></i></div>
                    </a>

                 </div>
             </div> <!-- item end -->

              <div class="columns item">
                 <div class="item-wrap">

                    <a href="#" data-imagelightbox="a" >
                       <%= image_tag 'screenshots/spot-uv-logo.jpg' %>
                       <div class="overlay"></div>
                       <div class="link-icon"><i class="icon-plus"></i></div>
                    </a>

                 </div>
             </div> <!-- item end -->

              <div class="columns item">
                 <div class="item-wrap">

                    <a href="#" data-imagelightbox="a" >
                     <%= image_tag 'screenshots/tshirt-mockup.jpg' %>
                       <div class="overlay"></div>
                       <div class="link-icon"><i class="icon-plus"></i></div>
                    </a>

                 </div>
             </div> <!-- item end -->

              <div class="columns item">
                 <div class="item-wrap">

                    <a href="#" data-imagelightbox="a" >
                       <%= image_tag 'screenshots/abstract-vector.jpg' %>
                       <div class="overlay"></div>
                       <div class="link-icon"><i class="icon-plus"></i></div>
                    </a>

                 </div>
             </div> <!-- item end -->

              <div class="columns item">
                 <div class="item-wrap">

                    <a href="#" data-imagelightbox="a" >
                       <%= image_tag 'screenshots/embossed-paper.jpg' %>
                       <div class="overlay"></div>
                       <div class="link-icon"><i class="icon-plus"></i></div>
                    </a>

                 </div>
             </div> <!-- item end -->

              <div class="columns item">
                 <div class="item-wrap">

                    <a href="#" data-imagelightbox="a" >
                       <%= image_tag 'screenshots/judah.jpg' %>
                       <div class="overlay"></div>
                       <div class="link-icon"><i class="icon-plus"></i></div>
                    </a>

                 </div>
             </div>  <!-- item end -->

           </div> <!-- portfolio-wrapper end -->

        </div> <!-- twelve columns end -->

     </div>  <!-- end row -->

  </section> <!-- Screenshots End -->


  <!-- Call-To-Action Section
  ================================================== -->
  <section id="call-to-action">

     <div class="row">

        <div class="seven columns">

           <h2>すべての機能を使うには</h2>
           <p>???にはこんな機能やあんな機能があります。もしあなたが全ての機能を使いたいならサインアップしてください。
</p>

        </div>

        <div class="three columns action">

           <a href="http://www.rakulacook.com/user/regist/" class="button">Sign Up Now</a>

        </div>

     </div>

  </section> <!-- Call-To-Action Section End-->



  <!-- Features Section
  ================================================== -->
  <section id='features'>

     <div class="row feature design">

        <div class="six columns right">
           <h3>特徴その１</h3>

           <p>Lorem ipsum dolor sit amet, ea eum labitur scripserit, illum complectitur deterruisset at pro. Odio quaeque reformidans est eu, expetendis intellegebat has ut, viderer invenire ut his. Has molestie percipit an. Falli volumus efficiantur sed id, ad vel noster propriae. Ius ut etiam vivendo, graeci iudicabit constituto at mea. No soleat fabulas prodesset vel, ut quo solum dicunt.
           Nec et amet vidisse mentitum. Cibo mutat nulla ei eam.
           </p>
        </div>

        <div class="six columns feature-media left">
            <%= image_tag 'feature-image-1.png' %>
        </div>

     </div>

     <div class="row feature responsive">

        <div class="six columns left">
           <h3>特徴その２</h3>

           <p>Aenean condimentum, lacus sit amet luctus lobortis, dolores et quas molestias excepturi
           enim tellus ultrices elit, amet consequat enim elit noneas sit amet luctu.
           Quis nostrum exercitationem ullam corporis suscipit laboriosam.Our library is continually refreshed with the latest on web technology
           so you'll never fall behind. Quis nostrum exercitationem ullam corporis suscipit laboriosam.
           </p>
        </div>

        <div class="six columns feature-media right">
              <%= image_tag 'feature-image-2.png' %>
        </div>

     </div>

     <div class="row feature cross-browser">

        <div class="six columns right">
           <h3>特徴その３</h3>

           <p>Lorem ipsum dolor sit amet, ea eum labitur scripserit, illum complectitur deterruisset at pro. Odio quaeque reformidans est eu, expetendis intellegebat has ut, viderer invenire ut his. Has molestie percipit an. Falli volumus efficiantur sed id, ad vel noster propriae. Ius ut etiam vivendo, graeci iudicabit constituto at mea. No soleat fabulas prodesset vel, ut quo solum dicunt.
           Nec et amet vidisse mentitum. Cibo mutat nulla ei eam.
           </p>
        </div>

        <div class="six columns feature-media left">
            <%= image_tag 'feature-image-3.png' %>
        </div>

     </div>


  </section> <!-- Homepage Hero end -->
<%= render 'layouts/footer' %>

app/views/user_pages/confirm.html.erb
<h1>確認</h1>

<%= form_for @user, :url => {:controller => "user_pages"} do |f| %>
    名前: <%= @user.name %>
    <%= f.hidden_field :name %>
    <br />
    メールアドレス: <%= @user.email %>
    <%= f.hidden_field :email %>
    <br />
    パスワード: <%= @user.password %>
    <%= f.hidden_field :password %>
    <br />
    <%= f.submit '戻る', name: "back" %>
    <br />
    <%= f.submit '登録'%>
<% end %>

<%= render 'layouts/footer' %>

app/views/user_pages/login.html.erb
<h1>UserPages#login</h1>
<p>Find me in app/views/user_pages/login.html.erb</p>
<%= render 'layouts/footer' %>

app/views/user_pages/profile.html.erb
<h1>UserPages#profile</h1>
<p>Find me in app/views/user_pages/profile.html.erb</p>
<%= render 'layouts/footer' %>

app/views/user_pages/regist.html.erb
<h1>会員登録</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for @user, :url => {:controller => "user_pages", :action => "confirm"} do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name, "名前" %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email, "メールアドレス" %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password, "パスワード" %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "パスワード（確認）" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "確認", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

<%= render 'layouts/footer' %>

app/views/user_pages/show.html.erb

<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <!-- <%= gravatar_for @user %> -->
        <%= @user.name %>
      </h1>
    </section>
  </aside>
</div>
<%= render 'layouts/footer' %>